# GitHub Actions workflow
name: MLOps Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Preprocessing
        run: python src/data/preprocess.py

      - name: Run Training
        run: python src/models/train.py

      - name: Run Evaluation
        run: python src/models/evaluate.py